# Copyright 2021-2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/> .

require allow_fortran_tests

standard_testfile ".f90"
load_lib fortran.exp

if {[prepare_for_testing ${testfile}.exp ${testfile} ${srcfile} \
	 {debug additional_flags=-fopenmp f90}]} {
    return -1
}

if ![fortran_runto_main] {
    return -1
}

gdb_breakpoint [gdb_get_line_number "Breakpoint"]
gdb_continue_to_breakpoint "Breakpoint"
gdb_test "frame" "#0\[ \t\]*__omp_offloading.*"

gdb_test "print i1" "= 26"
gdb_test "print r1" "= 2.5"
gdb_test "print r2" "= 4.5"
gdb_test "print c1" "= \\(2.5,4.5\\)"
gdb_test "print str1" "= 'Flang'"
gdb_test "print str2" "= 'Fortran   '"
gdb_test "print arr1" "= \\(5, 6, 5, 5, 5, 5, 5, 5, 5, 5\\)"
gdb_test "print i2" "= 36"
gdb_test "print r3" "= 12.5"
gdb_test "print r4" "= 14.5"
gdb_test "print c2" "= \\(12.5,14.5\\)"
gdb_test "print l1" "= .FALSE."
gdb_test "print l2" "= .TRUE."
gdb_test "print arr2" "= \\(\\(35, 2, 3\\) \\(4, 5, 6\\) \\(7, 8, 9\\) \\(10, 11, 12\\)\\)"
